# Generated by Django 3.0.4 on 2020-03-21 20:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0004_auto_20200321_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestVPR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название теста')),
                ('description', models.TextField(verbose_name='Краткое описание теста')),
                ('done', models.TextField(verbose_name='Список уже выполнивших тест')),
            ],
        ),
        migrations.AddField(
            model_name='answervpr',
            name='test_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionvpr',
            name='corr_ans',
            field=models.CharField(blank=True, max_length=100, verbose_name='Верный ответ'),
        ),
        migrations.AlterField(
            model_name='questionvpr',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='questionvpr',
            name='num_ex',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер задания ВПР'),
        ),
    ]
