# Generated by Django 3.0.4 on 2020-03-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0005_auto_20200321_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testvpr',
            name='description',
            field=models.TextField(blank=True, verbose_name='Краткое описание теста'),
        ),
        migrations.AlterField(
            model_name='testvpr',
            name='done',
            field=models.TextField(blank=True, verbose_name='Список уже выполнивших тест'),
        ),
    ]
