# Generated by Django 3.0.4 on 2020-03-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0006_auto_20200321_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='answervpr',
            name='is_corr',
            field=models.BooleanField(blank=True, default=0, verbose_name='Верный ли ответ'),
        ),
    ]
