# Generated by Django 3.0.4 on 2020-03-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0009_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Название задания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents_upload', verbose_name='Добавить файл'),
        ),
    ]
