# Generated by Django 3.0.4 on 2020-03-26 20:11

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0010_auto_20200324_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsEx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents_upload/', verbose_name='Добавить файл')),
            ],
        ),
        migrations.AlterField(
            model_name='exercise',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents_upload/', verbose_name='Добавить файл'),
        ),
    ]
