# Generated by Django 3.0.4 on 2020-03-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0012_ansex_ex_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansex',
            name='is_check',
            field=models.BooleanField(default=False),
        ),
    ]
