# Generated by Django 3.0.4 on 2020-04-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0013_ansex_is_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='testvpr',
            name='time',
            field=models.IntegerField(blank=True, default=0, verbose_name='Время на выполнение задание в минутах'),
        ),
    ]
