# Generated by Django 3.0.4 on 2020-04-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0014_testvpr_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestVPR_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('test_id', models.IntegerField(verbose_name='id теста')),
            ],
        ),
    ]
