# Generated by Django 3.0.4 on 2020-04-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0017_cruduser_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='KR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('time', models.IntegerField(default=10, verbose_name='Время в минутах')),
                ('done', models.TextField(verbose_name='Уже делали')),
            ],
        ),
        migrations.DeleteModel(
            name='CrudUser',
        ),
    ]
