# Generated by Django 3.0.4 on 2020-04-13 18:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0018_auto_20200413_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsExKR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ответ')),
                ('ex_id', models.IntegerField(blank=True, null=True)),
                ('is_corr', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExKR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Задание')),
                ('corr_ans', models.CharField(blank=True, max_length=100, verbose_name='Верный ответ')),
                ('kr_id', models.IntegerField(verbose_name='Ключ связи с кр')),
            ],
        ),
    ]
