# Generated by Django 3.0.4 on 2020-04-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0020_krst'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansexkr',
            name='kr_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
