# Generated by Django 3.0.4 on 2020-04-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0022_auto_20200419_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansexkr',
            name='ans',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Ответ'),
        ),
    ]
