# Generated by Django 3.0.4 on 2020-08-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0023_auto_20200419_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='kr',
            name='groups',
            field=models.TextField(blank=True, default=';', null=True, verbose_name='Задано следующим группам'),
        ),
    ]
