# Generated by Django 3.0.4 on 2020-08-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0024_kr_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansex',
            name='us_id',
            field=models.IntegerField(blank=True, default=-1, verbose_name='ID ученика'),
        ),
        migrations.AddField(
            model_name='ansexkr',
            name='us_id',
            field=models.IntegerField(blank=True, default=-1, verbose_name='ID ученика'),
        ),
        migrations.AddField(
            model_name='answervpr',
            name='us_id',
            field=models.IntegerField(blank=True, default=-1, verbose_name='ID ученика'),
        ),
        migrations.AddField(
            model_name='krst',
            name='us_id',
            field=models.IntegerField(blank=True, default=-1, verbose_name='ID ученика'),
        ),
        migrations.AddField(
            model_name='testvpr_student',
            name='us_id',
            field=models.IntegerField(blank=True, default=-1, verbose_name='ID ученика'),
        ),
    ]
