# Generated by Django 3.0.4 on 2020-08-01 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0025_auto_20200801_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answervpr',
            name='name',
        ),
    ]
