# Generated by Django 3.0.4 on 2020-08-01 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0029_auto_20200801_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='krst',
            name='name',
        ),
        migrations.RemoveField(
            model_name='krst',
            name='surname',
        ),
    ]
