# Generated by Django 3.0.4 on 2020-08-01 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0031_auto_20200801_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ansex',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ansex',
            name='surname',
        ),
    ]
