# Generated by Django 3.0.4 on 2020-08-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0036_auto_20200804_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='exkr',
            name='file',
            field=models.FileField(blank=True, upload_to='', verbose_name='Файл, прикрепленный к заданию'),
        ),
    ]
