# Generated by Django 3.0.4 on 2020-08-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0037_exkr_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exkr',
            name='file',
            field=models.FileField(blank=True, upload_to='documents_upload/', verbose_name='Файл, прикрепленный к заданию'),
        ),
    ]
