# Generated by Django 3.0.4 on 2020-08-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0038_auto_20200807_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansexkr',
            name='file',
            field=models.FileField(blank=True, upload_to='documents_upload/', verbose_name='Файл, ответ на задание(при необходимости)'),
        ),
    ]
