# Generated by Django 3.0.4 on 2020-08-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0039_ansexkr_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansexkr',
            name='number_ans',
            field=models.IntegerField(blank=True, default=1, verbose_name='Какой по счету ответ на задание от ученика'),
        ),
    ]
