# Generated by Django 3.0.4 on 2020-08-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0041_statskr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exkr',
            name='file',
        ),
        migrations.AddField(
            model_name='exkr',
            name='ans_file',
            field=models.BooleanField(blank=True, default=False, verbose_name='Ответ - файл'),
        ),
    ]
