# Generated by Django 3.0.4 on 2020-08-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0042_auto_20200813_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='exkr',
            name='file',
            field=models.FileField(blank=True, upload_to='documents_upload/', verbose_name='Файл, прикрепленный к заданию'),
        ),
    ]
