# Generated by Django 3.0.4 on 2020-08-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0043_exkr_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='exkr',
            name='points',
            field=models.IntegerField(default=1, verbose_name='Количество баллов за задание'),
        ),
    ]
