# Generated by Django 3.0.4 on 2020-08-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0044_exkr_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansexkr',
            name='points',
            field=models.IntegerField(default=1, verbose_name='Полученные баллы за задание'),
        ),
    ]
