# Generated by Django 3.0.4 on 2020-08-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0045_ansexkr_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='statskr',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Набранные за работу баллы'),
        ),
    ]
