# Generated by Django 3.0.4 on 2020-08-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0049_auto_20200820_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_info1', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('text_info2', models.CharField(blank=True, max_length=200, verbose_name='Текст/место/дата...')),
                ('file', models.ImageField(blank=True, upload_to='photos_upload/', verbose_name='Фото')),
            ],
        ),
    ]
