# Generated by Django 3.0.4 on 2020-08-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0050_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='', verbose_name='Resize photo'),
            preserve_default=False,
        ),
    ]
