# Generated by Django 3.0.4 on 2020-08-25 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0051_photo_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='thumbnail',
        ),
    ]
