# Generated by Django 3.0.4 on 2020-08-28 10:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0052_remove_photo_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название задания')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Задание')),
                ('file', models.FileField(blank=True, null=True, upload_to='students_works_upload/', verbose_name='Добавить файл')),
            ],
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
