# Generated by Django 3.0.4 on 2020-08-28 10:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0053_auto_20200828_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsworks',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Работа ученика'),
        ),
        migrations.AlterField(
            model_name='studentsworks',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
