# Generated by Django 3.0.4 on 2021-07-05 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0055_videolesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoLesson',
        ),
    ]
