# Generated by Django 3.0.4 on 2021-07-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0056_delete_videolesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='exkr',
            name='ans_text',
            field=models.BooleanField(blank=True, default=False, verbose_name='Ответ - текст'),
        ),
    ]
