# Generated by Django 3.0.4 on 2021-07-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='num_class',
            field=models.CharField(blank=True, max_length=200, verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='subj',
            field=models.TextField(blank=True, verbose_name='Предмет'),
        ),
    ]
