# Generated by Django 3.0.4 on 2021-07-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_lessons', '0002_auto_20210706_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='tag_subj',
            field=models.TextField(blank=True, verbose_name='Тэг предмета'),
        ),
    ]
