# Generated by Django 3.0.4 on 2021-07-06 23:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_lessons', '0003_videolesson_tag_subj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolesson',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Конспект'),
        ),
    ]
