# Generated by Django 3.0.4 on 2021-07-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_lessons', '0004_auto_20210706_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolesson',
            name='description',
        ),
        migrations.AddField(
            model_name='videolesson',
            name='annotation_file',
            field=models.FileField(blank=True, null=True, upload_to='annotation_upload/', verbose_name='Конспект'),
        ),
    ]
