# Generated by Django 3.0.4 on 2021-07-06 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_lessons', '0005_auto_20210706_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolesson',
            name='annotation_file',
            field=models.FileField(blank=True, null=True, upload_to='annotation_upload/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Конспект'),
        ),
    ]
